const place = [
    {
      "name":"Suisse",
      "Etymology":"La Suisse, en forme longue la Confédération suisse5 (en allemand Schweiz Écouter et Schweizerische Eidgenossenschaft, en italien Svizzera et Confederazione Svizzera, en romanche Svizra et Confederaziun svizra) est un pays d'Europe centrale et, selon certaines définitions, de l'Ouest, formé de 26 cantons6, avec Berne pour capitale de facto, parfois appelée « ville fédérale.",
      "History":"Depuis le milieu du xive siècle, le terme de confédération est employé pour qualifier les systèmes d'alliance qui se sont formés sur le territoire de la Suisse actuelle.",
      "Geography":"La Suisse est un pays d'Europe occidentale1 composé de 26 cantons souverains ayant pour capitale fédérale la ville de Berne. Elle est entourée de cinq pays : l'Autriche et le Liechtenstein à l'est, l'Allemagne au nord, la France à l'ouest et l'Italie au sud, et ne dispose pas d'accès à la mer.<br><br>Les points extrêmes du pays se situent au nord à Oberbargen (canton de Schaffhouse), au sud à Chiasso (canton du Tessin), à l'ouest à Chancy (canton de Genève) et à l'est au Piz Chavalatsch (canton des Grisons). Le pays fait 350 km dans sa plus grande longueur et 220 km dans sa plus grande largeurBär.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Suisse",
      "Tourisme":"https://www.myswitzerland.com/en-nz/destinations/attractions/",
    },
    {
      "name":"Malaisie",
      "Etymology":"L'utilisation du nom de « Malaisie » pour désigner la péninsule malaise est récente. Ce nom est la francisation de Malaya dans l'expression « British Malaya » (Malaisie britannique) par laquelle les Britanniques désignaient, à partir de la fin du xixe siècle, les territoires qu'ils contrôlaient sur la péninsule.",
      "History":"Il y a très longtemps, la Malaisie était une péninsule inhabitée, recouverte par une forêt vieille de 130 millions d'années ayant échappé à toutes les glaciations. Ce n'est que vers 10 000 avant J.-C. qu'arrivèrent les premiers aborigènes.",
      "Geography":"La Malaisie péninsulaire (au Sud de la Thaïlande) est divisée du Nord au Sud par une longue chaîne montagneuse dont le point culminant se situe à 2 189 m (mont Tahan) et où subsistent de vastes zones forestières.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Malaisie",
      "Tourisme":"https://www.malaysia.travel/en/se",  
    },
    {
      "name":"Les États-Unis",
      "Etymology":"Les États-Unis sont une république fédérale composée de cinquante États fédérés auxquels s'ajoutent le district de Columbia — comprenant la capitale Washington — et plusieurs territoires.",
      "History":"Au cours de l'histoire des États-Unis, le pouvoir fédéral a eu tendance à se renforcer au détriment des États et la question du droit des États demeure en débat aux États-Unis.",
      "Geography":"La géographie des États-Unis consiste en l'étude du territoire des États-Unis, pays d'Amérique du Nord s'étendant de l'océan Pacifique à l'ouest à l'océan Atlantique à l'est sur une superficie de 9 600 000 km2, ce qui en fait le quatrième pays le plus vaste sur Terre. Il est bordé au nord par le Canada et au sud par le Mexique.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/%C3%89tats_des_%C3%89tats-Unis",
      "Tourisme":"https://www.usa.gov/state-travel-and-tourism",  
    },
    {
      "name":"Islande",
      "Etymology":"L'Islande (en islandais : Ísland [ˈistlant]b, littéralement « terre de glace »), en forme longue la république d'Islande (Lýðveldið Ísland)a, est un pays insulaire d'Europe du Nord situé dans l'océan Atlantique. ",
      "History":"L'histoire de l'Islande est récente par rapport à celle du reste de l'Europe. Du fait de son éloignement, ce pays n'a pas subi la guerre, mais certains événements extérieurs, tels que la réforme protestante imposée par le Danemark ou la peste noire, ont eu des conséquences importantes pour les Islandais. L'histoire du pays a aussi été marquée par nombre de catastrophes naturelles et par sa lutte pour l'indépendance, obtenue le 17 juin 1944.",
      "Geography":"Île de l'océan Atlantique nord, située entre le Groenland et la Norvège, au nord-ouest des îles Féroé, l'Islande s'étend sur 102 775 km25. Son relief, culminant à 2 109,6 m au Hvannadalshnjúkur, est assez montagneux, le centre de l'île constituant les Hautes Terres d'Islande désertiques et les côtes découpées par des fjords. Plus de 10 % de l'île est constituée de glaciers. ",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Islande",
      "Tourisme":"https://www.inspiredbyiceland.com/",  
    },
    {
      "name":"Indonesie",
      "Etymology":"Le nom « Indonésie » est un néologisme tiré des mots grecs Indos, signifiant « Indien », et nêsos, signifiant « île »5. Ce nom date du xixe siècle, bien avant la formation de l'Indonésie indépendante6.",
      "History":"Le 17 août 1945, Soekarno et Hatta, proclament l’indépendance de l'Indonésie, jusqu'alors appelée Indes orientales néerlandaises. Après quatre années de conflit armé et diplomatique que les Indonésiens appellent Revolusi, les Pays-Bas reconnaissent l'indépendance de l'Indonésie le 27 décembre 1949, à l'exception de la Nouvelle-Guinée occidentale, dont le statut sera discuté ultérieurement.",
      "Geography":"Selon le CIA World Factbook, l'Indonésie est constituée de 13 466 îles1. D'après des estimations du gouvernement indonésien en 2008, 922 d'entre elles sont habitées.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Indonesie",
      "Tourisme":"https://www.indonesia.travel/gb/en/home",  
    },
    {
      "name":"Japon",
      "Etymology":"En japonais, « Japon » (日本) se dit Nihon ou Nippon, et éventuellement dans les documents administratifs Nipponkoku (日本国) prononcé plus rarement Nihonkoku, soit « Nation japonaise ». La forme abrégée Ni- (日), toujours en préfixe, sert parfois dans un but qualificatif : ainsi trouve-t-on Nicchū (日中)13 pour l'adjectif « nippo-chinois » ou « sino-japonais »14. Le nom Japon est un exonyme, en effet c'est une prononciation chinoise transmise ensuite aux Occidentaux.",
      "History":"Le Japon est peuplé depuis le paléolithique. Une présence humaine y est indiquée par l'archéologie sur plusieurs niveaux de fouille depuis plus de 12 000 ans ; celle-ci débute par l'arrivée des Aïnous, peuple indigène paléo-sibérien, les premiers habitants de l'archipel japonais. À la faveur du réchauffement climatique suivant la glaciation de Würm, les Aïnous sont restés isolés de l'Eurasie et ont développé une forme de culture fondée sur la chasse, la cueillette et la pêche qui a perduré jusqu'au début du xxe siècle.",
      "Geography":"L'État du Japon forme, dans l'Est de l'Asie, un archipel de 6 852 îles de plus de 100 m2 sur plus de trois mille kilomètres de long, face à la Russie (îles Kouriles), Taïwan, la Corée et la Chine44. Quatre de ces îles — du nord au sud, Hokkaidō (79 000 km2), historiquement peuplée par les Aïnous, Honshū (227 000 km2) la plus grande et la plus peuplée avec 105 millions d'habitants, Shikoku (18 000 km2) qui est l'île de la mer intérieure et Kyūshū (36 000 km2) — représentent l'essentiel d'un territoire de 377 975 km25 (95 % du territoire des 4 000 îles de l'arc insulaire).",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Japon",
      "Tourisme":"https://www.japan.travel/en/",  
    },
    {
      "name":"UK",
      "Etymology":"Le Royaume-Uni (prononcé en français : /ʁwajom‿yni/a Écouter), en forme longue le Royaume-Uni de Grande-Bretagne et d'Irlande du Nordb (en anglais : United Kingdom /juːˌnaɪtɪd ˈkɪŋdəm/c Écouter et United Kingdom of Great Britain and Northern Ireland)d, est un pays d'Europe de l'Ouest, ou selon certaines définitions, d'Europe du Nord, dont le territoire comprend l'île de Grande-Bretagne et la partie nord de l'île d'Irlande, ainsi que de nombreuses petites îles autour de l'archipel. ",
      "History":"Les royaumes d'Angleterre et d'Écosse ont cohabité en tant que nations souveraines et indépendantes avec leurs propres monarques et structures politiques depuis le ixe siècle.",
      "Geography":"La majeure partie de l'Angleterre a un relief très varié hormis le Nord et la péninsule de Cornouailles. Les deux principaux fleuves sont la Tamise (346 km) et la Severn (354 km) qui est le plus long cours d'eau du Royaume-Uni. Près de la ville de Douvres (en anglais : Dover), le tunnel sous la Manche relie la Grande-Bretagne à la France.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Royaume-Uni",
      "Tourisme":"https://www.visitbritain.com/gb/en",  
    },
    {
      "name":"Italie",
      "Etymology":"Au ve siècle av. J.-C. le nom Italia désigne à l'origine une partie seulement de ce qu'est maintenant l'Italie du Sud.",
      "History":"Avant le développement de Rome, l'Italie était composée de plusieurs cultures et civilisations, pour la plupart indo-européennes (Italiotes ou italiques), sur un substrat ligure du Néolithique. Sur ces cultures qualifiées d'autochtones, empiétaient :",
      "Geography":"L'Italie est une péninsule de l'Europe du Sud située au centre du bassin méditerranéen. D'une superficie de 301 300 km2, elle est longue de 1 360 km du nord au sud et couvre à 92 % la superficie de la région géographique italienne.",
      "Wikipedia":"https://fr.wikipedia.org/wiki/Italie",
      "Tourisme":"http://www.italia.it/en/home.html",  
    },
]